#!/bin/sh

echo "Hook fired: push-mud2net"

cd ~/fun/mud2net
echo $PWD
git fetch origin
git reset --hard origin/master
docker build -t mud2net .
docker stop mud2net
docker rm mud2net
docker run --name mud2net -p 8000:3000 -e NEW_RELIC_LICENSE_KEY="$NEW_RELIC_LICENSE_KEY" -e NEW_RELIC_APP_NAME="mud2.net" -d mud2net

docker stop nginx-vhosts
docker rm nginx-vhosts
docker run --name nginx-vhosts -p 80:80 --link sykartdata:sykartdata --link blog:blog --link mud2net:mud2net -d nginx-vhosts
