#!/bin/sh

echo "Hook fired: push-nginx-docker-vhosts"

cd ~/fun/nginx-docker-vhosts
echo $PWD
git fetch origin
git reset --hard origin/master
docker build -t nginx-vhosts .
docker stop nginx
docker rm nginx
docker run --name nginx-vhosts -p 80:80 --link sykartdata:sykartdata --link blog:blog --link mud2net:mud2net -d nginx -a